on:
  workflow_run:
    workflows: ["CodeSee Map Generate"]
    types:
      - completed

name: CodeSee Map Upload and Insights

jobs:
  test_map_action:
    runs-on: ubuntu-latest
    if: >
      ${{ (github.event.worklow_run.event == 'pull_request' ||
            github.event.worklow_run.event == 'push') &&
          github.event.workflow_run_conclusion == 'success' }}
    name: Run map action on action code
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Fetch Codesee Map Artifact
        uses: actions/github-script@v5
        with:
          script: |
            var artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.event.workflow_run.id }},
            });
            var matchArtifacts = artifacts.data.artifacts.find((artifact) => artifact.name === 'codesee-map-file');
            var download = await github.rest.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: matchArtifacts.id,
              archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/codesee.map.json.zip', Buffer.from(download.data));

      - name: Unzip artifact
        run: unzip codesee.map.json.zip -d ${{github.workspace}}

      - name: Set Event Name From Previous Run
        run: |
          PREVIOUS_EVENT_NAME=$(cat event_name.txt)
          echo "PREVIOUS_EVENT_NAME=$PREVIOUS_EVENT_NAME" >> $GITHUB_ENV

      - name: Upload Map
        id: upload-map
        uses: Codesee-io/codesee-map-action@1829-fix-pull-requests
        with:
          step: mapUpload
          api_token: ${{ secrets.CODESEE_ARCH_DIAG_API_TOKEN }}
          github_ref: ${{ github.ref }}
          with_event_data: event.json
          with_event_name: ${{ env.PREVIOUS_EVENT_NAME }}

      - name: Insights
        id: insights
        uses: Codesee-io/codesee-map-action@1829-fix-pull-requests
        with:
          step: insights
          api_token: ${{ secrets.CODESEE_ARCH_DIAG_API_TOKEN }}
          github_ref: ${{ github.ref }}
          with_event_data: event.json
          with_event_name: ${{ env.PREVIOUS_EVENT_NAME }}
